site_name: Knuckles

repo_url: https://github.com/kutu-dev/knuckles
repo_name: kutu-dev/knuckles

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - content.code.copy

nav:
  - Home:
      Home: "index.md"
      Contributing: "contributing.md"
  - Reference: "reference/"

plugins:
- search
- gen-files:
    scripts:
    - scripts/generate-reference-pages.py
- literate-nav:
    nav_file: summary.md
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: true
            show_if_no_docstring: true
          merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji
