site_name: Knuckles

repo_url: https://github.com/kutu-dev/knuckles
repo_name: kutu-dev/knuckles

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Home: "index.md"
  - Reference: "reference/"

plugins:
- search
- gen-files:
    scripts:
    - scripts/generate-reference-pages.py
- literate-nav:
    nav_file: summary.md
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: true
            show_if_no_docstring: true
          merge_init_into_class: true

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.emoji
