name: Linting and formatting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_pre_commit:
    runs-on: ubuntu-24.04

    steps:
      - run: sudo apt-get install -y just
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11.9"
      - run: just setup
      - run: just check
