name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-24.04
    permissions:
        contents: write

    steps:
      - run: sudo apt-get install -y just
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-${{ hashFiles('requirements/requirements-docs.txt') }}
      - run: just setup-docs
      - run: just deploy-docs
